name: Update Maricv branch

on:
  push:
    branches:
      - main

jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge changes from main into Maricv
        run: |
          git checkout Maricv
          git pull origin main
          git push origin Maricv
