name: Update Branches

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Maricv branch if it does not exist
        run: |
          if ! git show-ref --verify --quiet refs/heads/Maricv; then
            git checkout -b Maricv
            git push origin Maricv
          fi

      - name: Merge changes into Maricv branch
        run: |
          git checkout Maricv
          git merge main
          git push origin Maricv
